from typing import Protocol

from app.domain.models import ExamSessionRecord, Paper, SubmissionRecord


class Repository(Protocol):
    # M10-03: owner_id 参数 = 可见性作用域（None 不过滤=auth off/内部读取；
    # 给定用户 = 系统公共卷 + 自有卷），双实现语义一致
    async def list_papers(self, owner_id: str | None = None) -> list[Paper]: ...

    async def get_paper(self, paper_id: str, owner_id: str | None = None) -> Paper | None: ...

    async def create_exam(self, paper: Paper, mode: str) -> ExamSessionRecord: ...

    async def get_exam(self, exam_id: str) -> ExamSessionRecord | None: ...

    async def save_answer(self, exam_id: str, sequence: int, question_id: str, answer: str) -> ExamSessionRecord: ...

    async def submit(self, exam_id: str) -> SubmissionRecord: ...

    async def get_submission(self, exam_id: str) -> SubmissionRecord | None: ...
