from typing import Protocol

from app.domain.models import ExamSessionRecord, Paper, SubmissionRecord


class Repository(Protocol):
    async def list_papers(self) -> list[Paper]: ...

    async def get_paper(self, paper_id: str) -> Paper | None: ...

    async def create_exam(self, paper: Paper, mode: str) -> ExamSessionRecord: ...

    async def get_exam(self, exam_id: str) -> ExamSessionRecord | None: ...

    async def save_answer(self, exam_id: str, sequence: int, question_id: str, answer: str) -> ExamSessionRecord: ...

    async def submit(self, exam_id: str) -> SubmissionRecord: ...

    async def get_submission(self, exam_id: str) -> SubmissionRecord | None: ...
